# Generated by Django 5.2.10 on 2026-01-26 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_create_categories'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodCod', models.AutoField(primary_key=True, serialize=False)),
                ('prodCode', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Codigo del Producto')),
                ('prodDescr', models.TextField(editable=False, verbose_name='Descripcion del Producto')),
                ('prodMarca', models.CharField(max_length=25, verbose_name='Marca')),
                ('prodMate', models.CharField(choices=[('A', 'Acetato'), ('M', 'Metal'), ('TR', 'TR'), ('C', 'Carey'), ('N', 'No aplica')], default='N', max_length=2, verbose_name='Material')),
                ('prodColor', models.CharField(blank=True, max_length=20, verbose_name='Color')),
                ('prodTalla', models.CharField(blank=True, max_length=20, verbose_name='Talla/Tamano')),
                ('prodGenero', models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Unisex', 'Unisex'), ('Nino', 'Nino')], default='Unisex', max_length=20, verbose_name='Genero')),
                ('prodCostoInv', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Compra')),
                ('prodPrecioVenta', models.DecimalField(decimal_places=2, help_text='Precio al que vendes el producto', max_digits=10, verbose_name='Precio de Venta')),
                ('prodStock', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('prodStockMin', models.IntegerField(default=0, verbose_name='Stock Minimo')),
                ('prodEstado', models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion')),
                ('catproCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.productcategory', verbose_name='Categoria')),
                ('provCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
            },
        ),
    ]
