# Generated by Django 5.2.10 on 2026-01-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodColor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodCostoInv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodDescr',
            field=models.TextField(editable=False, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodGenero',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Unisex', 'Unisex'), ('Nino', 'Nino')], default='Unisex', max_length=10, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodMarca',
            field=models.CharField(blank=True, help_text='Obligatorio para monturas, opcional para accesorios', max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodMate',
            field=models.CharField(choices=[('A', 'Acetato'), ('M', 'Metal'), ('TR', 'TR'), ('C', 'Carey'), ('N', 'No aplica')], default='N', help_text='Solo para monturas', max_length=2, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodPrecioVenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodStock',
            field=models.IntegerField(default=1, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodTalla',
            field=models.CharField(blank=True, help_text='Ej: 54-18-140', max_length=20, verbose_name='Talla'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
