# Generated by Django 5.2.7 on 2026-02-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodDescripcionAdicional',
            field=models.TextField(blank=True, help_text='Informacion adicional del producto', verbose_name='Descripcion Adicional'),
        ),
        migrations.AddField(
            model_name='product',
            name='prodForma',
            field=models.CharField(blank=True, help_text='Ej: Redondo, Cuadrado, Aviador', max_length=30, verbose_name='Forma'),
        ),
        migrations.AddField(
            model_name='product',
            name='prodTieneSobrelente',
            field=models.BooleanField(default=False, help_text='Indica si la montura incluye sobrelente', verbose_name='Tiene Sobrelente'),
        ),
    ]
