# Generated by Django 5.2.10 on 2026-02-07 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_create_generic_luna_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunaCaracteristica',
            fields=[
                ('lunCarCod', models.AutoField(primary_key=True, serialize=False)),
                ('lunCarNombre', models.CharField(max_length=100, unique=True)),
                ('lunCarDescripcion', models.TextField(blank=True)),
                ('lunCarPrecioAdicional', models.DecimalField(decimal_places=2, default=0, help_text='Costo extra de esta característica', max_digits=10, verbose_name='Precio Adicional')),
                ('lunCarActivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Característica de Luna',
                'verbose_name_plural': 'Características de Luna',
                'db_table': 'luna_caracteristica',
            },
        ),
        migrations.CreateModel(
            name='LunaMaterial',
            fields=[
                ('lunMatCod', models.AutoField(primary_key=True, serialize=False)),
                ('lunMatNombre', models.CharField(max_length=50, unique=True)),
                ('lunMatDescripcion', models.TextField(blank=True)),
                ('lunMatActivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material de Luna',
                'verbose_name_plural': 'Materiales de Luna',
                'db_table': 'luna_material',
            },
        ),
        migrations.CreateModel(
            name='LunaTipo',
            fields=[
                ('lunTipCod', models.AutoField(primary_key=True, serialize=False)),
                ('lunTipNombre', models.CharField(max_length=50, unique=True)),
                ('lunTipDescripcion', models.TextField(blank=True)),
                ('lunTipActivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Luna',
                'verbose_name_plural': 'Tipos de Luna',
                'db_table': 'luna_tipo',
            },
        ),
        migrations.CreateModel(
            name='LunaConfiguracion',
            fields=[
                ('lunConfCod', models.AutoField(primary_key=True, serialize=False)),
                ('lunConfPrecioBase', models.DecimalField(decimal_places=2, help_text='Precio sin características adicionales', max_digits=10, verbose_name='Precio Base')),
                ('lunConfActivo', models.BooleanField(default=True)),
                ('lunConfObservaciones', models.TextField(blank=True)),
                ('lunMatCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.lunamaterial', verbose_name='Material')),
                ('lunTipCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.lunatipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Configuración de Luna',
                'verbose_name_plural': 'Configuraciones de Luna',
                'db_table': 'luna_configuracion',
                'unique_together': {('lunMatCod', 'lunTipCod')},
            },
        ),
    ]
