# Generated by Django 5.2.7 on 2026-02-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_load_luna_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunacaracteristica',
            options={'ordering': ['lunCarNombre'], 'verbose_name': 'Característica de Luna', 'verbose_name_plural': 'Características de Luna'},
        ),
        migrations.AlterModelOptions(
            name='lunaconfiguracion',
            options={'ordering': ['lunMatCod', 'lunTipCod'], 'verbose_name': 'Configuración de Luna', 'verbose_name_plural': 'Configuraciones de Luna'},
        ),
        migrations.AlterModelOptions(
            name='lunamaterial',
            options={'ordering': ['lunMatNombre'], 'verbose_name': 'Material de Luna', 'verbose_name_plural': 'Materiales de Luna'},
        ),
        migrations.AlterModelOptions(
            name='lunatipo',
            options={'ordering': ['lunTipNombre'], 'verbose_name': 'Tipo de Luna', 'verbose_name_plural': 'Tipos de Luna'},
        ),
        migrations.RemoveField(
            model_name='lunaconfiguracion',
            name='lunConfObservaciones',
        ),
        migrations.AlterField(
            model_name='lunacaracteristica',
            name='lunCarActivo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='lunacaracteristica',
            name='lunCarDescripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='lunacaracteristica',
            name='lunCarNombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Característica'),
        ),
        migrations.AlterField(
            model_name='lunacaracteristica',
            name='lunCarPrecioAdicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Adicional'),
        ),
        migrations.AlterField(
            model_name='lunaconfiguracion',
            name='lunConfActivo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='lunaconfiguracion',
            name='lunConfPrecioBase',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base'),
        ),
        migrations.AlterField(
            model_name='lunamaterial',
            name='lunMatActivo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='lunamaterial',
            name='lunMatDescripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='lunamaterial',
            name='lunMatNombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='lunatipo',
            name='lunTipActivo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='lunatipo',
            name='lunTipDescripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='lunatipo',
            name='lunTipNombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tipo'),
        ),
    ]
