# Generated by Django 5.2.10 on 2026-02-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpticalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optNom', models.CharField(max_length=255)),
                ('optLema', models.CharField(blank=True, max_length=255, null=True)),
                ('optDir', models.TextField(blank=True, null=True)),
                ('optProv', models.TextField(blank=True, null=True)),
                ('optTel', models.CharField(blank=True, max_length=15, null=True)),
                ('optLogo', models.ImageField(blank=True, null=True, upload_to='company/')),
            ],
        ),
    ]
