# Generated by Django 5.2.10 on 2026-01-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('catproCod', models.AutoField(primary_key=True, serialize=False)),
                ('catproCode', models.CharField(max_length=5, unique=True, verbose_name='Código de Categoría')),
                ('catproNom', models.CharField(max_length=20, unique=True, verbose_name='Nombre de Categoría')),
            ],
        ),
    ]
