# Generated by Django 5.2.10 on 2026-02-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_add_luna_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='catproRequiereInventario',
            field=models.BooleanField(default=True, help_text='False para lunas personalizadas', verbose_name='Requiere Control de Inventario'),
        ),
    ]
