# Generated by Django 5.2.7 on 2026-02-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_add_requiere_inventario_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='catproRequiereInventario',
            field=models.BooleanField(default=True, help_text='Si False, los productos no consumen stock (ej: Lunas Personalizadas)', verbose_name='Requiere Inventario'),
        ),
    ]
