# Generated by Django 5.2.10 on 2026-01-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_type', models.CharField(help_text='Material (A, M, TR, C) o GENERAL para no monturas', max_length=10, unique=True, verbose_name='Tipo de Secuencia')),
                ('current_value', models.IntegerField(default=0, help_text='Ultimo numero asignado', verbose_name='Valor Actual')),
                ('description', models.CharField(blank=True, help_text='Descripcion del tipo de secuencia', max_length=50, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion')),
            ],
            options={
                'verbose_name': 'Secuencia de Producto',
                'verbose_name_plural': 'Secuencias de Productos',
                'db_table': 'product_sequence',
                'ordering': ['sequence_type'],
            },
        ),
    ]
