# Generated by Django 5.2.10 on 2026-01-28 22:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('clients', '0001_initial'),
        ('products', '0002_alter_product_options_alter_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('comprCod', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Comprobante')),
                ('comprSerie', models.CharField(default='NV01', max_length=4, verbose_name='Serie')),
                ('comprCorrelativo', models.IntegerField(verbose_name='Correlativo')),
                ('comprFechaEmision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Emision')),
                ('comprNombreCliente', models.CharField(max_length=200, verbose_name='Nombre Cliente')),
                ('comprDocumentoCliente', models.CharField(blank=True, max_length=50, verbose_name='Documento Cliente')),
                ('comprSubtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('comprDescuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('comprTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('comprAnulado', models.BooleanField(default=False, verbose_name='Anulado')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'db_table': 'comprobante',
                'ordering': ['-comprFechaEmision'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteDetalle',
            fields=[
                ('comprDetCod', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Detalle')),
                ('comprDetDescripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('comprDetCantidad', models.IntegerField(verbose_name='Cantidad')),
                ('comprDetPrecioUni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('comprDetSubtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('comprDetDescuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('comprDetTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('comprCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.comprobante', verbose_name='Comprobante')),
                ('prodCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante',
                'verbose_name_plural': 'Detalles de Comprobante',
                'db_table': 'comprobante_detalle',
                'ordering': ['comprDetCod'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventCod', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Venta')),
                ('ventFecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Venta')),
                ('ventFechaEntrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega Estimada')),
                ('ventEstado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Pago Parcial'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado Pago')),
                ('ventEstadoRecoj', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LISTO', 'Listo para recoger'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado Pedido')),
                ('ventSubTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('ventDescuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento Total')),
                ('ventTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('ventAdelanto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Adelanto')),
                ('ventSaldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo')),
                ('ventObservaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ventAnulada', models.BooleanField(default=False, verbose_name='Anulada')),
                ('ventMotivoAnulacion', models.TextField(blank=True, verbose_name='Motivo Anulacion')),
                ('ventFormaPago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('MIXTO', 'Pago Mixto')], default='EFECTIVO', max_length=15, verbose_name='Forma de Pago')),
                ('ventReferenciaPago', models.CharField(blank=True, max_length=50, verbose_name='Referencia de Pago')),
                ('ventTarjetaTipo', models.CharField(blank=True, choices=[('DEBITO', 'Debito'), ('CREDITO', 'Credito'), ('', 'No Aplica')], max_length=10, verbose_name='Tipo de Tarjeta')),
                ('cajaAperCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.cashopening', verbose_name='Caja asociada')),
                ('cliCod', models.ForeignKey(blank=True, help_text='Dejar vacio para cliente generico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clients.client', verbose_name='Cliente')),
                ('usuCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['-ventFecha'],
            },
        ),
        migrations.AddField(
            model_name='comprobante',
            name='ventCod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='sales.venta', verbose_name='Venta asociada'),
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('ventDetCod', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Detalle')),
                ('ventDetCantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('ventDetPrecioUni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('ventDetSubtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('ventDetDescuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('ventDetTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('ventDetAnulado', models.BooleanField(default=False, verbose_name='Anulado')),
                ('ventDetDescripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('ventDetMarca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('prodCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto')),
                ('ventCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'venta_detalle',
                'ordering': ['ventDetCod'],
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['-ventFecha'], name='venta_ventFec_a85570_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['ventEstado'], name='venta_ventEst_8966cb_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['comprSerie', 'comprCorrelativo'], name='comprobante_comprSe_85c5b8_idx'),
        ),
    ]
