# Generated by Django 5.2.10 on 2026-02-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='ventEstadoRecoj',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LABORATORIO', 'En Laboratorio'), ('LISTO', 'Listo para recoger'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado Pedido'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetDescripcion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetPrecioUni',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetSubtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
    ]
