# Generated by Django 5.2.7 on 2026-02-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_venta_ventestadorecoj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='ventFormaPago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('VISA', 'Visa')], default='', max_length=15, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventTarjetaTipo',
            field=models.CharField(blank=True, choices=[('VISA', 'Visa'), ('', 'No Aplica')], max_length=10, verbose_name='Tipo de Tarjeta'),
        ),
    ]
