# Generated by Django 5.2.7 on 2026-02-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_venta_ventformapago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='esLunaPersonalizada',
            field=models.BooleanField(default=False, verbose_name='Es Luna Personalizada'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='lunaCaracteristicas',
            field=models.TextField(blank=True, help_text='Ej: Blue Block, Fotocromático, Anti-reflejo (separadas por comas)', verbose_name='Características Adicionales'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='lunaCostoLaboratorio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo que cobró el laboratorio', max_digits=10, null=True, verbose_name='Costo del Laboratorio'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='lunaLaboratorio',
            field=models.CharField(blank=True, help_text='Laboratorio que fabricó la luna', max_length=100, verbose_name='Laboratorio Proveedor'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='lunaMaterial',
            field=models.CharField(blank=True, help_text='Ej: Orgánico, Policarbonato, Cristal', max_length=50, verbose_name='Material de Luna'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='lunaTipo',
            field=models.CharField(blank=True, help_text='Ej: Monofocal, Bifocal, Multifocal, Progresivo', max_length=50, verbose_name='Tipo de Luna'),
        ),
    ]
