# Generated by Django 5.2.7 on 2026-02-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_ventadetalle_eslunapersonalizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='ventEstadoRecoj',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LISTO', 'Listo para recoger'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado Pedido'),
        ),
    ]
