# Generated by Django 5.2.7 on 2026-02-07 01:01

from django.db import migrations


def migrate_laboratorio_to_listo(apps, schema_editor):
    """
    Convierte todos los registros en estado LABORATORIO a LISTO
    """
    Venta = apps.get_model('sales', 'Venta')
    
    # Actualizar ventas en estado LABORATORIO a LISTO
    ventas_actualizadas = Venta.objects.filter(ventEstadoRecoj='LABORATORIO').update(ventEstadoRecoj='LISTO')
    
    if ventas_actualizadas > 0:
        print(f"✅ {ventas_actualizadas} ventas actualizadas de LABORATORIO a LISTO")


def reverse_migration(apps, schema_editor):
    """
    Función de reversión (no hace nada, no podemos saber qué ventas eran LABORATORIO)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_laboratorio_status'),
    ]

    operations = [
        migrations.RunPython(migrate_laboratorio_to_listo, reverse_migration),
    ]
