# Generated by Django 5.2.7 on 2026-02-07 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_migrate_laboratorio_to_listo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labNombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Laboratorio')),
                ('labActivo', models.BooleanField(default=True, verbose_name='Activo')),
                ('labFechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'db_table': 'laboratorio',
                'ordering': ['labNombre'],
            },
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='lunaLaboratorio',
            field=models.CharField(blank=True, help_text='Campo legacy - usar ForeignKey laboratorio', max_length=100, verbose_name='Laboratorio Proveedor (Legacy)'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='laboratorio',
            field=models.ForeignKey(blank=True, help_text='Laboratorio que fabricó la luna', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunas', to='sales.laboratorio', verbose_name='Laboratorio'),
        ),
    ]
