# Generated by Django 5.2.10 on 2026-02-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_laboratorio_alter_ventadetalle_lunalaboratorio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventadetalle',
            name='laboratorio',
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='lunaLaboratorio',
            field=models.CharField(blank=True, help_text='Laboratorio que fabricó la luna', max_length=100, verbose_name='Laboratorio Proveedor'),
        ),
        migrations.DeleteModel(
            name='Laboratorio',
        ),
    ]
