# Generated by Django 5.2.10 on 2026-02-09 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_ventadetalle_laboratorio_and_more'),
        ('suppliers', '0005_create_internal_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='lunaLaboratorio',
            field=models.ForeignKey(blank=True, help_text='Laboratorio que fabricó la luna', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lunas_suministradas', to='suppliers.supplier', verbose_name='Laboratorio Proveedor'),
        ),
    ]
