# Generated by Django 5.2.10 on 2026-01-26 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cliCod', models.AutoField(primary_key=True, serialize=False)),
                ('cliTipoDoc', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de extranjeria')], default='DNI', max_length=10)),
                ('cliNumDoc', models.CharField(max_length=20, unique=True)),
                ('cliNombre', models.CharField(default='', max_length=100)),
                ('cliApellido', models.CharField(default='', max_length=100)),
                ('cliTelef', models.CharField(max_length=9)),
                ('cliFechaNac', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Optometrist',
            fields=[
                ('optCod', models.AutoField(primary_key=True, serialize=False)),
                ('optNombre', models.CharField(max_length=100)),
                ('optApellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recCod', models.AutoField(primary_key=True, serialize=False)),
                ('recFech', models.DateField(auto_now_add=True)),
                ('recEstado', models.CharField(default='Activo', max_length=50)),
                ('recObservaciones', models.TextField(blank=True, null=True)),
                ('recInfoExtra', models.TextField(blank=True, null=True)),
                ('receDIP', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('receDIPCerca', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('receAdd', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('receEsfeOD', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('receCilinOD', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('receEjeOD', models.IntegerField(blank=True, null=True)),
                ('receAvccOD', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('receEsfeOI', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('receCilinOI', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('receEjeOI', models.IntegerField(blank=True, null=True)),
                ('receAvccOI', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('receEsExterna', models.BooleanField(default=False)),
                ('diagnostico', models.JSONField(blank=True, default=list)),
                ('cliCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='clients.client')),
                ('optCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes_realizadas', to='clients.optometrist')),
            ],
        ),
    ]
