# Generated by Django 5.2.10 on 2026-01-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cliApellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='cliNombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='cliNumDoc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cliTelef',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cliTipoDoc',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CE', 'Carnet de extranjeria')], default='DNI', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recEstado',
            field=models.CharField(blank=True, default='Activo', max_length=50, null=True),
        ),
    ]
