# Generated by Django 5.2.10 on 2026-01-31 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_cliapellido_alter_client_clinombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cliApellido',
            new_name='cliNomCompleto',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cliNombre',
        ),
    ]
