# Generated by Django 5.2.10 on 2026-01-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_cliapellido_client_clinomcompleto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='receAdd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='receDIP',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='receDIPCerca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
