# Generated by Django 5.2.10 on 2026-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_recipe_receadd_alter_recipe_recedip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='receCilinOD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='receCilinOI',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='receEsfeOD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='receEsfeOI',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
