# Generated by Django 5.2.7 on 2026-02-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_recipe_rececilinod_alter_recipe_rececilinoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cliTipoDoc',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet de extranjeria')], default='DNI', max_length=10, null=True),
        ),
    ]
