# Generated by Django 5.2.10 on 2026-02-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_clitipodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='receAvccOD',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='receAvccOI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='receDIP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='receDIPCerca',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
