# Generated by Django 5.2.10 on 2026-01-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('rolCod', models.AutoField(primary_key=True, serialize=False)),
                ('rolNom', models.CharField(choices=[('GERENTE', 'Gerente'), ('CAJERO', 'Cajero'), ('VENDEDOR', 'Vendedor'), ('OPTOMETRA', 'Optometra'), ('LOGISTICA', 'Logística')], max_length=50)),
                ('rolDes', models.CharField(max_length=50)),
                ('rolEstado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('rolNivel', models.IntegerField(choices=[(0, 'Nivel 0'), (1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuCod', models.AutoField(primary_key=True, serialize=False)),
                ('usuNom', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('usuNombreCom', models.CharField(max_length=60)),
                ('usuDNI', models.CharField(max_length=8)),
                ('usuTel', models.CharField(max_length=9)),
                ('usuEmail', models.EmailField(max_length=254, unique=True)),
                ('usuEstado', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('roles', models.ManyToManyField(to='users.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
