# Generated by Django 5.2.10 on 2026-01-26 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('provCod', models.AutoField(primary_key=True, serialize=False, verbose_name='Supplier Code')),
                ('provRuc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='RUC must be exactly 11 digits', regex='^\\d{11}$')], verbose_name='RUC')),
                ('provRazSocial', models.CharField(max_length=255, verbose_name='Razon Social')),
                ('provDirec', models.TextField(verbose_name='Address')),
                ('provTele', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Phone must be exactly 9 digits', regex='^\\d{9}$')], verbose_name='Phone')),
                ('provEmail', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('provCiu', models.CharField(max_length=100, verbose_name='City')),
                ('provEstado', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status')),
            ],
        ),
    ]
