# Generated by Django 5.2.7 on 2026-02-05 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_provciu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='provCiu',
            field=models.CharField(blank=True, choices=[('AMAZONAS', 'Amazonas'), ('ANCASH', 'Áncash'), ('APURIMAC', 'Apurímac'), ('AREQUIPA', 'Arequipa'), ('AYACUCHO', 'Ayacucho'), ('CAJAMARCA', 'Cajamarca'), ('CALLAO', 'Callao'), ('CUSCO', 'Cusco'), ('HUANCAVELICA', 'Huancavelica'), ('HUANUCO', 'Huánuco'), ('ICA', 'Ica'), ('JUNIN', 'Junín'), ('LA_LIBERTAD', 'La Libertad'), ('LAMBAYEQUE', 'Lambayeque'), ('LIMA', 'Lima'), ('LORETO', 'Loreto'), ('MADRE_DE_DIOS', 'Madre de Dios'), ('MOQUEGUA', 'Moquegua'), ('PASCO', 'Pasco'), ('PIURA', 'Piura'), ('PUNO', 'Puno'), ('SAN_MARTIN', 'San Martín'), ('TACNA', 'Tacna'), ('TUMBES', 'Tumbes'), ('UCAYALI', 'Ucayali')], max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='provDirec',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='provEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='provRuc',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='RUC must be exactly 11 digits', regex='^\\d{11}$')], verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='provTele',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Phone must be exactly 9 digits', regex='^\\d{9}$')], verbose_name='Phone'),
        ),
    ]
