# Generated by Django 5.2.10 on 2026-01-28 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('cajCod', models.AutoField(primary_key=True, serialize=False)),
                ('cajNom', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Caja')),
                ('cajDes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('cajEstado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'cash',
                'ordering': ['cajNom'],
            },
        ),
        migrations.CreateModel(
            name='CashOpening',
            fields=[
                ('cajaAperCod', models.AutoField(primary_key=True, serialize=False)),
                ('cajaApertuFechHora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Apertura')),
                ('cajaAperMontInicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Inicial')),
                ('cajaAperFechaHorCierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cierre')),
                ('cajaAperMontCierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Cierre')),
                ('cajaAperMontEsperado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Esperado')),
                ('cajaAperDiferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferencia')),
                ('cajaAperEstado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=10, verbose_name='Estado')),
                ('cajaAperObservacio', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cajCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas', to='cash.cash', verbose_name='Caja')),
                ('usuCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Apertura de Caja',
                'verbose_name_plural': 'Aperturas de Caja',
                'db_table': 'cash_opening',
                'ordering': ['-cajaApertuFechHora'],
            },
        ),
    ]
